### PR TITLE
Add the 1_000_000 limit like we do for CSV exports

### PR DESCRIPTION
**Pull request by mathijsblokland**
I'm using the Asq api in Learning Trends (Edutrends) and would like to use 1 call instead of looping through 11 calls to fetch all the data i need.

### CODE REVIEW

**Comment by djfpaagman** [comment]
:ship:

**Comment by timflapper** [comment]
I'm not sure if this is a good idea. Doesn't this mean that we will always return all results for all queries? That's going to go badly wrong for queries that return a lot of data.

**Comment by mathijsblokland** [comment]
This isn't for all asq queries but only the API access, on the other hand maybe doing 11 (or more) calls is a better approach.

**Comment by bittersweet** [comment]
So then, closing it :) Paging is indeed good for now.

**Comment by djfpaagman** [comment]
🤘

**Pull request closed without merging**
